/**
 * One definition of what a name is.
 *
 * profiles.name is private and profiles.display_name is the public projection
 * of it, generated by Postgres. These helpers exist so the server writes a name
 * whose projection is the first name and nothing else, and so a test can pin the
 * TypeScript and the SQL to the same rule instead of hoping they agree.
 *
 * The rule that matters: no part of a surname may become publicly selectable.
 * Splitting on ASCII spaces alone was not enough. A name joined by a
 * non-breaking space (which is what a paste from a document or a phone keyboard
 * often gives you) has no ASCII space in it at all, so the whole string survives
 * the split and the surname is public.
 *
 * Separators are built from their code points on purpose. A literal one in the
 * source is invisible in review, which is the whole problem.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  NAME_MAX,
  deriveInitials,
  normalizeFullName,
  publicDisplayName
} from './profile-identity';

const CODE_POINTS = [
  0x20, // space
  0x09, // tab
  0x0a, // line feed
  0x0d, // carriage return
  0x0c, // form feed
  0x0b, // vertical tab
  0xa0, // no-break space
  0x1680, // ogham space mark
  0x2007, // figure space
  0x200a, // hair space
  0x200b, // zero width space
  0x2028, // line separator
  0x2029, // paragraph separator
  0x202f, // narrow no-break space
  0x205f, // medium mathematical space
  0x3000, // ideographic space
  0xfeff // zero width no-break space
];
const SEPARATORS = CODE_POINTS.map(c => String.fromCharCode(c));

describe('normalizeFullName', () => {
  it('trims and collapses the ordinary cases', () => {
    expect(normalizeFullName('  Ada   Lovelace  ')).toBe('Ada Lovelace');
    expect(normalizeFullName('Prince')).toBe('Prince');
    expect(normalizeFullName('Ada')).toBe('Ada');
  });

  it('treats every kind of space as a space', () => {
    for (const separator of SEPARATORS) {
      expect(normalizeFullName(`  Ada${separator}${separator}Lovelace${separator}`)).toBe('Ada Lovelace');
    }
  });

  it('answers with an empty string rather than throwing on rubbish', () => {
    expect(normalizeFullName('')).toBe('');
    expect(normalizeFullName('   ')).toBe('');
    expect(normalizeFullName(SEPARATORS.join(''))).toBe('');
    expect(normalizeFullName(null)).toBe('');
    expect(normalizeFullName(undefined)).toBe('');
    expect(normalizeFullName(42)).toBe('');
    expect(normalizeFullName({ name: 'Ada' })).toBe('');
  });

  it('does not silently truncate, so the caller can refuse a long name', () => {
    const long = 'A'.repeat(NAME_MAX + 10);
    expect(normalizeFullName(long)).toHaveLength(NAME_MAX + 10);
  });
});

describe('publicDisplayName', () => {
  it('is the first name and nothing else', () => {
    expect(publicDisplayName('Ada Lovelace')).toBe('Ada');
    expect(publicDisplayName('  Ada   Byron Lovelace ')).toBe('Ada');
    expect(publicDisplayName('Prince')).toBe('Prince');
  });

  it('never lets a surname through on an unusual separator', () => {
    for (const separator of SEPARATORS) {
      const projected = publicDisplayName(`Ada${separator}Lovelace`);
      expect(projected).toBe('Ada');
      expect(projected).not.toMatch(/Lovelace/);
    }
  });

  it('is empty for an empty name', () => {
    expect(publicDisplayName('')).toBe('');
    expect(publicDisplayName('   ')).toBe('');
    expect(publicDisplayName(null)).toBe('');
  });
});

describe('deriveInitials', () => {
  it('keeps what the avatars have always shown', () => {
    expect(deriveInitials('Ada Lovelace')).toBe('AL');
    expect(deriveInitials('Prince')).toBe('P');
    expect(deriveInitials('Ada Byron Lovelace')).toBe('AB');
    expect(deriveInitials('  ada   lovelace ')).toBe('AL');
  });

  it('handles the same separators the projection does', () => {
    for (const separator of SEPARATORS) {
      expect(deriveInitials(`Ada${separator}Lovelace`)).toBe('AL');
    }
  });

  it('is empty rather than broken for an empty name', () => {
    expect(deriveInitials('')).toBe('');
    expect(deriveInitials(null)).toBe('');
  });
});

describe('the TypeScript rule and the SQL rule are the same rule', () => {
  const expand = readFileSync(
    join(process.cwd(), 'supabase', 'migrations', '20260805211500_conversation_withdrawal.sql'),
    'utf8'
  );
  const generated = expand.match(/GENERATED ALWAYS AS \(([\s\S]*?)\) STORED/)?.[1] ?? '';

  it('generates display_name from a separator class, not from a plain space', () => {
    expect(generated).toMatch(/regexp_replace/);
    expect(generated).toMatch(/split_part/);
    expect(generated).toMatch(/btrim/);
  });

  it('collapses in SQL every code point the TypeScript side collapses', () => {
    // The Postgres pattern is written with \uXXXX escapes, and ranges cover the
    // runs. Each code point above has to be inside the class one way or another.
    const klass = generated.match(/'(\[[^\]']*\])\+?'/)?.[1] ?? '';
    expect(klass).not.toBe('');

    const ranges = [...klass.matchAll(/\\u([0-9a-f]{4})-\\u([0-9a-f]{4})/gi)]
      .map(m => [parseInt(m[1], 16), parseInt(m[2], 16)] as const);
    const singles = new Set(
      [...klass.matchAll(/\\u([0-9a-f]{4})/gi)].map(m => parseInt(m[1], 16))
    );
    const ascii: Record<string, number> = { t: 0x09, n: 0x0a, r: 0x0d, f: 0x0c, v: 0x0b };
    for (const [letter, code] of Object.entries(ascii)) {
      if (klass.includes(`\\${letter}`)) singles.add(code);
    }
    if (/\[ |\s\]/.test(klass) || klass.includes('[ ')) singles.add(0x20);

    for (const point of CODE_POINTS) {
      const covered = singles.has(point) || ranges.some(([lo, hi]) => point >= lo && point <= hi);
      expect(covered, `SQL class does not cover U+${point.toString(16).padStart(4, '0')}`).toBe(true);
    }
  });

  it('is still a stored generated column, so no client can desync it', () => {
    expect(expand).toMatch(/ADD COLUMN IF NOT EXISTS display_name TEXT\s+GENERATED ALWAYS AS/);
    expect(expand).toMatch(/\) STORED;/);
    expect(expand).not.toMatch(/CREATE TRIGGER[^;]*display_name/i);
  });
});
